### ISSUE TITLE
Missing/invalid `cards` property and `tma` unknown value cause repeated log errors

### ISSUE THREAD

**Issue by freeztyler** [mk-maddin/wattpilot-HA#114]
### Is there an existing issue for this?

- [x] I have searched the existing and already closed issues

### The problem

The Wattpilot integration is repeatedly writing errors to the Home Assistant log.

The device does not seem to provide the `cards` property, or it does not return it as a list. The integration still treats `cards` as a namespacelist and tries to index the returned fallback value. This causes repeated errors like:

ERROR (MainThread) [custom_components.wattpilot.utils] wattpilot - GetChargerProp: Charger does not have property: cards
ERROR (MainThread) [custom_components.wattpilot.entities] Wattpilot Ladesäule - cards: async_update failed: 'int' object is not subscriptable (builtins.TypeError)

I also saw a related error for `tma` / charger temperature:

ERROR (MainThread) [custom_components.wattpilot.entities] Wattpilot Ladesäule - tma: async_local_push failed: Sensor sensor.wattpilot_ladesaule_charger_temp has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>) (builtins.ValueError)

Integration version: 0.3.7

### Describe the issue you are experiencing

The integration assumes that `cards` exists and is a list. On my Wattpilot, `cards` is missing or not returned as a list. The integration then indexes the fallback/default value and raises `TypeError: 'int' object is not subscriptable`.

For `tma`, the integration writes string `unknown` to a numeric temperature sensor, which Home Assistant rejects.3

### Describe the expected behavior

Missing optional properties like `cards` should not create repeated error log entries. The related entities should stay unavailable or be skipped when the property is missing or not a list.

Numeric sensors such as `tma` should not write string `unknown` as their native numeric value. They should keep the previous valid value, become unavailable, or return no update.

### Steps To Reproduce

1. Install and configure the Wattpilot integration version 0.3.7.
2. Connect it to a Wattpilot device that does not provide the `cards` property, or does not return `cards` as a list.
3. Restart Home Assistant.
4. Open the Home Assistant log.
5. The log repeatedly shows errors for `cards`, for example:
   ERROR (MainThread) [custom_components.wattpilot.utils] wattpilot - GetChargerProp: Charger does not have property: cards
   ERROR (MainThread) [custom_components.wattpilot.entities] Wattpilot Ladesäule - cards: async_update failed: 'int' object is not subscriptable (builtins.TypeError)

Optional related issue:
6. If the charger temperature property `tma` returns no valid numeric value, the log also shows an error because the temperature sensor receives string `unknown`.

### What version of Home Assistant Core is installed?

io.hass.base.version	: 2026.05.0, io.hass.type: core, io.hass.version: 2026.6.0

### What version of Wattpilot integration is installed?

0.3.7

### What type of Wattpilot Charger are you using?

11KW

**Comment by Jojonabi** [comment]
## Environment

- Home Assistant: 2026.7.4
- Wattpilot Integration: 0.3.8
- Wattpilot Model: Wattpilot Flex
- Wattpilot Firmware: 4.3.4

## Description

I can confirm that this issue still exists with version **0.3.8** of the Wattpilot integration.

The repeated `cards` and `tma` errors are identical to those already described in this issue.

In addition, I also see entity initialization errors that do not appear to be mentioned here.

## Log excerpts

### Missing `cards` property

```text
wattpilot - GetChargerProp: Charger does not have property: cards
Wattpilot - cards: async_update failed: 'int' object is not subscriptable
```

### Charger temperature (`tma`)

```text
Wattpilot - tma: async_local_push failed:
Sensor sensor.wattpilot_xxx_wattpilot_charger_temp
has the non-numeric value: 'unknown' (<class 'str'>)
```

### Entity initialization

```text
AttributeError: 'ChargerSensor' object has no attribute '_entity_category'
```

This prevents several `sensor.unnamed_device` entities from being created.

During initialization I also see missing charger properties including:

- `bac`
- `ust`
- `tse`
- `upo`
- `ccw`
- `cus`
- `ffb`
- `lck`

## Impact

The main functionality of the Wattpilot integration appears to work correctly.

However:

- some entities are not created,
- the charger temperature sensor cannot be updated,
- and the Home Assistant log is continuously filled with repeated error messages.

### Additional tracebacks

The following traceback is repeated for several `sensor.unnamed_device_*` entities:

```text
2026-07-26 12:44:35.031 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.unnamed_device_9 for domain sensor with platform wattpilot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 726, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1085, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1443, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 307, in async_internal_added_to_hass
    if self.entity_category == EntityCategory.CONFIG:
       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattpilot/entities.py", line 162, in entity_category
    if not self._entity_category is None:
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChargerSensor' object has no attribute '_entity_category'. Did you mean: 'entity_category'?
```

The charger temperature sensor also repeatedly receives the string `unknown` instead of a numeric value:

```text
2026-07-26 12:41:48.672 ERROR (MainThread) [custom_components.wattpilot.entities] Wattpilot - tma: async_local_push failed: Sensor sensor.wattpilot_XXXXXXXX_wattpilot_charger_temp has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>) (builtins.ValueError)
```

The `tma` error is repeated continuously with the same content.

**Comment by andmaramo** [comment]
# Environment
Home Assistant: 2026.8.2
Wattpilot Integration: shows 0.3.7 (downloaded 0.3.8)
Wattpilot Model: Wattpilot Flex Home 11 C6
Wattpilot Firmware: 43.4

# Description
Same as already mentioned.

# Log excerpts

### missing property
wattpilot - GetChargerProp: Charger does not have property: tse
wattpilot - GetChargerProp: Charger does not have property: upo
wattpilot - GetChargerProp: Charger does not have property: ffb
wattpilot - GetChargerProp: Charger does not have property: lck
wattpilot - GetChargerProp: Charger does not have property: cards

Wattpilot - cus: __init__: Charger does not have a property: cus (maybe an attribute?)
Wattpilot - tse: __init__: Charger does not have a property: tse (maybe an attribute?)
Wattpilot - upo: __init__: Charger does not have a property: upo (maybe an attribute?)
Wattpilot - ffb: __init__: Charger does not have a property: ffb (maybe an attribute?)
Wattpilot - lck: __init__: Charger does not have a property: lck (maybe an attribute?)

### cards async_update failed 
Wattpilot - cards: async_update failed: 'int' object is not subscriptable (builtins.TypeError)

### temperature error
Wattpilot - tma: async_local_push failed: Sensor sensor.wattpilot_91136401_wattpilot_charger_temp has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>) (builtins.ValueError)
Wattpilot - tma: async_local_push failed: Sensor sensor.keller_wattpilot_charger_temp has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'unknown' (<class 'str'>) (builtins.ValueError)


### unnamed devices
Error adding entity sensor.unnamed_device_6 for domain sensor with platform wattpilot
Error adding entity sensor.unnamed_device_7 for domain sensor with platform wattpilot
Error adding entity sensor.unnamed_device_8 for domain sensor with platform wattpilot
Error adding entity sensor.unnamed_device_9 for domain sensor with platform wattpilot
Error adding entity sensor.unnamed_device_10 for domain sensor with platform wattpilot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1104, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1443, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 309, in async_internal_added_to_hass
    if self.entity_category == EntityCategory.CONFIG:
       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wattpilot/entities.py", line 162, in entity_category
    if not self._entity_category is None:
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ChargerSensor' object has no attribute '_entity_category'. Did you mean: 'entity_category'?

### missing uniqe ID
Detected that custom integration 'wattpilot' attempts to attach a device to an entity without a unique ID. This will stop working in Home Assistant 2027.8.0, please report it to the author of the 'wattpilot' custom integration

**Comment by mstoffel-sag** [comment]
Confirming this on a newer setup, plus one finding about PR #118: it fixes the `cards` half completely, but its `sensor.py` hunk is a no-op on the push path.

**Environment**
- Integration: v0.3.8 (HACS)
- Home Assistant: 2026.9.0 (Docker container)
- Charger: Wattpilot 11 kW, firmware **43.1-rc4**, then **43.4**

**Firmware is not the cause**

I first suspected the RC firmware, so I upgraded 43.1-rc4 → 43.4. After two clean reconnects the error rate was identical. `cards` is absent and `tma` unusable on current stable firmware too, so this is not something users can fix by updating the charger.

Baseline on unmodified v0.3.8, measured over a 45-minute window (~50 errors/min, ~72k/day):

| Count | Message |
|---|---|
| 900 | `GetChargerProp: Charger does not have property: cards` |
| 890 | `cards: async_update failed: 'int' object is not subscriptable` |
| 508 | `tma: async_local_push failed: ... non-numeric value: 'unknown'` |
| 10 | `cards: __init__ failed: 'int' object is not subscriptable` |
| 7 | `bac`, `cus`, `ffb`, `lck`, `tse`, `upo`, `ust` — property missing |

Worth noting the 890 `async_update` errors originate in `available()`, not in `async_update` itself — `async_update` calls `self.available` at entities.py L254, and the unguarded subscript at L200 raises inside it. So PR #118's `available()` guard is what kills the bulk of the volume.

**Result of applying PR #118's source changes on top of v0.3.8**

| Error | Before | After |
|---|---|---|
| `GetChargerProp` spam | 900 | **0** |
| `cards: async_update failed` | 890 | **0** |
| `cards: __init__` | 10 | 10, now reported cleanly as `does not have a namespacelist item: cards[0]` |
| `tma` charger_temp ValueError | ~15/min | **unchanged** |

**Why the `tma` fix doesn't take effect**

`sensor.py` sets `_state_attr = '_attr_native_value'` (L84). PR #118 guards the assignment inside `_async_update_validate_platform_state`, but that function still **returns** `STATE_UNKNOWN`, and `async_local_push` in `entities.py` immediately writes it back unguarded:

```python
state = await self._async_update_validate_platform_state(state)
if not state is None:
    setattr(self, self._state_attr, state)   # reassigns STATE_UNKNOWN
    self.async_write_ha_state()              # ValueError raised here
```

So the guarded value is overwritten one line later. What worked for me was returning `None` so the caller skips its own `setattr`:

```python
if not self._attr_native_unit_of_measurement is None:
    if state == STATE_UNKNOWN:
        self._attr_native_value = None
        return None
    self._attr_native_value = state
return state
```

`None` is also the correct representation of "no value" for a numeric sensor. The `else` branch of `async_local_push` then calls `async_local_poll()`, which ends without a write and does not call back into push, so there is no recursion — I checked for that specifically.

With both changes the sustained rate is **0 errors/min**; only ~17 informational lines remain once per restart (the `cards[0..9]` and 7 missing-property notices), which seems like correct behaviour.

Two smaller things also still unguarded, though they don't fire for me because the charger never pushes a property it doesn't have: the same `state[int(self._namespace_id)]` subscript appears unguarded in `async_local_poll` (L321) and `async_local_push` (L347).

Separately, `sensor.wattpilot_charger_temp` reads a constant **999** here regardless of any of the above — that looks like #97 and is a different problem from the log spam.

For anyone hitting this before a fix lands, I put both changes on top of v0.3.8 here: https://github.com/mstoffel-sag/wattpilot-HA (release `v0.3.10`, installable as a HACS custom repository). It is upstream v0.3.8 plus PR #118's source changes plus the `sensor.py` follow-up above — nothing else.

Happy to open a PR with the `sensor.py` follow-up if useful.
