### ISSUE TITLE
Integration not working anymore

### ISSUE THREAD

**Issue by blurap** [mk-maddin/wattpilot-HA#75]
### Is there an existing issue for this?

- [x] I have searched the existing and already closed issues

### The problem

Great integration, thank you very much for it. I’ve been using it for months and it has always worked flawlessly. Today I noticed that our “Wattpilot” is no longer providing any data. The integration shows “Setup failed: Check the logs”. All entities are marked as “unavailable”. The last data I received was from June 21st, which is when a Home Assistant update was installed.

### Describe the issue you are experiencing

I found the following entries in the logs:

2025-06-25 08:56:41.970 ERROR (MainThread) [custom_components.wattpilot] 1646fabcbc9a804db1c2a59a49c5bc65 - async_setup_entry: Setup trigger for platform sensor failed: 'ConfigEntries' object has no attribute 'async_forward_entry_setup' (builtins.AttributeError)
2025-06-25 11:43:23.118 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'wattpilot' sets option flow config_entry explicitly, which is deprecated at custom_components/wattpilot/config_flow.py, line 89: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'wattpilot' custom integration
2025-06-25 11:47:06.979 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot: ConfigFlowHandler - async_get_options_flow
2025-06-25 11:47:06.979 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: __init__: <ConfigEntry entry_id=1646fabcbc9a804db1c2a59a49c5bc65 version=1 domain=wattpilot title=Wattpilot state=ConfigEntryState.SETUP_ERROR unique_id=None>
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: async_step_init: None
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: async_step_config_charger: None
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.configuration_schema] wattpilot - async_get_OPTIONS_CHARGER_SCHEMA

### Steps To Reproduce

Integration not working anymore.

### What version of Home Assistant Core is installed?

core-2025.6.3

### What version of Wattpilot integration is installed?

0.1.9

### What type of Wattpilot Charger are you using?

11KW

### Error message shown within HA log

2025-06-25 08:56:41.970 ERROR (MainThread) [custom_components.wattpilot] 1646fabcbc9a804db1c2a59a49c5bc65 - async_setup_entry: Setup trigger for platform sensor failed: 'ConfigEntries' object has no attribute 'async_forward_entry_setup' (builtins.AttributeError)
2025-06-25 11:43:23.118 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'wattpilot' sets option flow config_entry explicitly, which is deprecated at custom_components/wattpilot/config_flow.py, line 89: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'wattpilot' custom integration
2025-06-25 11:47:06.979 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot: ConfigFlowHandler - async_get_options_flow
2025-06-25 11:47:06.979 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: __init__: <ConfigEntry entry_id=1646fabcbc9a804db1c2a59a49c5bc65 version=1 domain=wattpilot title=Wattpilot state=ConfigEntryState.SETUP_ERROR unique_id=None>
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: async_step_init: None
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.config_flow] wattpilot - OptionsFlowHandler: async_step_config_charger: None
2025-06-25 11:47:06.988 DEBUG (MainThread) [custom_components.wattpilot.configuration_schema] wattpilot - async_get_OPTIONS_CHARGER_SCHEMA

### Anything else?

I really think the integration is great and have used it in many automations. It would be fantastic if you could help me soon. Many thanks in advance.

**Comment by DanielSzoska** [comment]
Probably same as #73 (very old version of the integration which is not compatible with HA 2025.6), please use the solution mentioned there.

**Comment by blurap** [comment]
Wow, thanks a lot for the immediate response. i've updated the integration and it works fine again. Thanks alot!
